# Generated by Django 5.1 on 2024-09-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_name", models.CharField(max_length=100)),
                ("pr_price", models.IntegerField()),
            ],
        ),
    ]
